apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.petclinic.replicaCount }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels: 
        name: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.petclinic.image }}:{{ .Values.petclinic.imageTag }}
        ports:
        - containerPort: {{ .Values.petclinic.containerPort }}